# Generated by Django 4.1.3 on 2022-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterialModel',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('subject_name', models.CharField(max_length=250)),
                ('material_file', models.FileField(null=True, upload_to='materials/')),
                ('videos', models.FileField(null=True, upload_to='videos/')),
                ('videos_link', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'StudyMaterials',
            },
        ),
    ]
