# Generated by Django 4.1.3 on 2022-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('s_id', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('face', models.ImageField(null=True, upload_to='images/')),
                ('status', models.CharField(default='pending', max_length=250)),
            ],
            options={
                'db_table': 'Student_details_table',
            },
        ),
    ]
