# Generated by Django 4.1.3 on 2022-12-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_sentiment', models.CharField(max_length=50)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('rating1', models.IntegerField(help_text='rating1', null=True)),
                ('rating2', models.IntegerField(help_text='rating2', null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentmodel')),
            ],
            options={
                'db_table': 'student_feedback',
            },
        ),
    ]
