# Generated by Django 4.1.3 on 2022-12-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentfeedbackmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedbackmodel',
            old_name='rating1',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='studentfeedbackmodel',
            old_name='rating2',
            new_name='video',
        ),
    ]
