# Generated by Django 4.1.3 on 2022-12-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('studentapp', '0003_rename_rating1_studentfeedbackmodel_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedbackmodel',
            name='stu_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.studymaterialmodel'),
        ),
    ]
