# Generated by Django 4.1.3 on 2022-12-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_studentfeedbackmodel_stu_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMediaModel',
            fields=[
                ('im_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'imagesource',
            },
        ),
    ]
