# Generated by Django 4.1.3 on 2022-12-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_tempmediamodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tempmediamodel',
            table='imagesource',
        ),
    ]
